/* Generated By:JJTree: Do not edit this line. ASTfun_stmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammar.generator;

public
class ASTfun_stmt extends SimpleNode {
  public ASTfun_stmt(int id) {
    super(id);
  }

  public ASTfun_stmt(CMM_PARSER p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CMM_PARSERVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6ce2c14a2dca3f08d4ff862050ae6013 (do not edit this line) */
