/* Generated By:JJTree: Do not edit this line. ASTif_stmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammar.generator;

public
class ASTif_stmt extends SimpleNode {
  public ASTif_stmt(int id) {
    super(id);
  }

  public ASTif_stmt(CMM_PARSER p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CMM_PARSERVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=66a95b077ccaa488a274cc5fa4cdfa58 (do not edit this line) */
