/* Generated By:JJTree: Do not edit this line. ASTstmt_seq1.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammar.generator;

public
class ASTstmt_seq1 extends SimpleNode {
  public ASTstmt_seq1(int id) {
    super(id);
  }

  public ASTstmt_seq1(CMM_PARSER p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CMM_PARSERVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ab4fd1a13da32e0ce92e46b270346c42 (do not edit this line) */
