/* Generated By:JavaCC: Do not edit this line. CMM_PARSERDefaultVisitor.java Version 7.0.10 */
package grammar.generator;

public class CMM_PARSERDefaultVisitor implements CMM_PARSERVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTprogram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTstmt_seq node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTstmt_seq1 node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTarg_stmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTfun_stmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTstmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTcall_stmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTif_stmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTass_stmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTloop_stmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTreturn_stmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTexp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTsimple_exp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTsimple_exp1 node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTterm node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTterm1 node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTfactor node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTepsilon node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=03674c577836fc6cd17134e4d5dde78f (do not edit this line) */
