/* Generated By:JavaCC: Do not edit this line. CMM_PARSERTreeConstants.java Version 7.0.10 */
package grammar.generator;

public interface CMM_PARSERTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTMT_SEQ = 1;
  public int JJTARG_STMT = 2;
  public int JJTFUN_STMT = 3;
  public int JJTSTMT = 4;
  public int JJTCALL_STMT = 5;
  public int JJTIF_STMT = 6;
  public int JJTASS_STMT = 7;
  public int JJTLOOP_STMT = 8;
  public int JJTRETURN_STMT = 9;
  public int JJTEXP = 10;
  public int JJTSIMPLE_EXP = 11;
  public int JJTSIMPLE_EXP1 = 12;
  public int JJTSUB = 13;
  public int JJTADD = 14;
  public int JJTTERM = 15;
  public int JJTTERM1 = 16;
  public int JJTDIV = 17;
  public int JJTMUL = 18;
  public int JJTFACTOR = 19;
  public int JJTNUM = 20;
  public int JJTEPSILON = 21;


  public String[] jjtNodeName = {
    "program",
    "stmt_seq",
    "arg_stmt",
    "fun_stmt",
    "stmt",
    "call_stmt",
    "if_stmt",
    "ass_stmt",
    "loop_stmt",
    "return_stmt",
    "exp",
    "simple_exp",
    "simple_exp1",
    "SUB",
    "ADD",
    "term",
    "term1",
    "DIV",
    "MUL",
    "factor",
    "NUM",
    "epsilon",
  };
}
/* JavaCC - OriginalChecksum=49d74d50b243ad185eb6c2518f0905ca (do not edit this line) */
