/* Generated By:JavaCC: Do not edit this line. CMM_PARSERVisitor.java Version 7.0.10 */
package grammar.generator;

public interface CMM_PARSERVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTprogram node, Object data);
  public Object visit(ASTstmt_seq node, Object data);
  public Object visit(ASTarg_stmt node, Object data);
  public Object visit(ASTfun_stmt node, Object data);
  public Object visit(ASTstmt node, Object data);
  public Object visit(ASTcall_stmt node, Object data);
  public Object visit(ASTif_stmt node, Object data);
  public Object visit(ASTass_stmt node, Object data);
  public Object visit(ASTloop_stmt node, Object data);
  public Object visit(ASTreturn_stmt node, Object data);
  public Object visit(ASTexp node, Object data);
  public Object visit(ASTsimple_exp node, Object data);
  public Object visit(ASTsimple_exp1 node, Object data);
  public Object visit(ASTSUB node, Object data);
  public Object visit(ASTADD node, Object data);
  public Object visit(ASTterm node, Object data);
  public Object visit(ASTterm1 node, Object data);
  public Object visit(ASTDIV node, Object data);
  public Object visit(ASTMUL node, Object data);
  public Object visit(ASTfactor node, Object data);
  public Object visit(ASTNUM node, Object data);
  public Object visit(ASTepsilon node, Object data);
}
/* JavaCC - OriginalChecksum=1c5f47fe3e3ba8234cc6d5b08565b071 (do not edit this line) */
