/* Generated By:JavaCC: Do not edit this line. CMM_PARSERVisitor.java Version 7.0.10 */
package grammar.generator;

public interface CMM_PARSERVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTprogram node, Object data);
  public Object visit(ASTstmt_seq node, Object data);
  public Object visit(ASTstmt_seq1 node, Object data);
  public Object visit(ASTarg_stmt node, Object data);
  public Object visit(ASTfun_stmt node, Object data);
  public Object visit(ASTstmt node, Object data);
  public Object visit(ASTcall_stmt node, Object data);
  public Object visit(ASTif_stmt node, Object data);
  public Object visit(ASTass_stmt node, Object data);
  public Object visit(ASTloop_stmt node, Object data);
  public Object visit(ASTreturn_stmt node, Object data);
  public Object visit(ASTexp node, Object data);
  public Object visit(ASTsimple_exp node, Object data);
  public Object visit(ASTsimple_exp1 node, Object data);
  public Object visit(ASTterm node, Object data);
  public Object visit(ASTterm1 node, Object data);
  public Object visit(ASTfactor node, Object data);
  public Object visit(ASTepsilon node, Object data);
}
/* JavaCC - OriginalChecksum=703b9a0ba6f3dde46202c1fe016f854a (do not edit this line) */
