/* CMM_PARSER.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. CMM_PARSER.java */
package grammar.generator;
import java.io.*;
import grammar.parser.Main;

public class CMM_PARSER/*@bgen(jjtree)*/implements CMM_PARSERTreeConstants, CMM_PARSERConstants {/*@bgen(jjtree)*/
  protected static JJTCMM_PARSERState jjtree = new JJTCMM_PARSERState();
    public static void main(String[] args) throws ParseException{
        CMM_PARSER parser = new CMM_PARSER(System.in);
        parser.program();
        System.out.println("Hello World");
    }

  static final public void program() throws ParseException {
    trace_call("program");
    try {
/*@bgen(jjtree) program */
  ASTprogram jjtn000 = new ASTprogram(JJTPROGRAM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        stmt_seq();
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("program");
    }
}

  static final public void stmt_seq() throws ParseException {
    trace_call("stmt_seq");
    try {
/*@bgen(jjtree) stmt_seq */
    ASTstmt_seq jjtn000 = new ASTstmt_seq(JJTSTMT_SEQ);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token id;
      try {
        id = jj_consume_token(ID);
        jj_consume_token(LS);
        if (jj_2_1(2)) {
          arg_stmt();
          jj_consume_token(RS);
          jj_consume_token(31);
          jj_consume_token(LB);
          fun_stmt();
          jj_consume_token(RB);
          stmt_seq1();
        } else if (jj_2_2(2)) {
          jj_consume_token(RS);
          jj_consume_token(31);
          jj_consume_token(LB);
          fun_stmt();
          jj_consume_token(RB);
          stmt_seq1();
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
jjtree.closeNodeScope(jjtn000, true);
                                                                                                                          jjtc000 = false;
jjtn000.value = id.image;
        Main.functions.add(id.image);
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("stmt_seq");
    }
}

  static final public void stmt_seq1() throws ParseException {
    trace_call("stmt_seq1");
    try {
/*@bgen(jjtree) stmt_seq1 */
  ASTstmt_seq1 jjtn000 = new ASTstmt_seq1(JJTSTMT_SEQ1);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_3(2)) {
          stmt_seq();
        } else {
          epsilon();
        }
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("stmt_seq1");
    }
}

  static final public void arg_stmt() throws ParseException {
    trace_call("arg_stmt");
    try {
/*@bgen(jjtree) arg_stmt */
 ASTarg_stmt jjtn000 = new ASTarg_stmt(JJTARG_STMT);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);Token id;
      try {
        id = jj_consume_token(ID);
        if (jj_2_4(2)) {
          jj_consume_token(SEM);
          arg_stmt();
        } else {
          epsilon();
        }
jjtree.closeNodeScope(jjtn000, true);
                                            jjtc000 = false;
jjtn000.value = id.image;
                                                  Main.functions.add(id.image);
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("arg_stmt");
    }
}

  static final public void fun_stmt() throws ParseException {
    trace_call("fun_stmt");
    try {
/*@bgen(jjtree) fun_stmt */
  ASTfun_stmt jjtn000 = new ASTfun_stmt(JJTFUN_STMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_5(2)) {
          stmt();
          fun_stmt();
        } else {
          epsilon();
        }
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("fun_stmt");
    }
}

  static final public void stmt() throws ParseException {
    trace_call("stmt");
    try {
/*@bgen(jjtree) stmt */
  ASTstmt jjtn000 = new ASTstmt(JJTSTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_6(2)) {
          if_stmt();
        } else if (jj_2_7(2)) {
          loop_stmt();
        } else if (jj_2_8(2)) {
          ass_stmt();
        } else if (jj_2_9(2)) {
          return_stmt();
        } else if (jj_2_10(2)) {
          call_stmt();
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("stmt");
    }
}

  static final public void call_stmt() throws ParseException {
    trace_call("call_stmt");
    try {
/*@bgen(jjtree) call_stmt */
ASTcall_stmt jjtn000 = new ASTcall_stmt(JJTCALL_STMT);
boolean jjtc000 = true;
jjtree.openNodeScope(jjtn000);Token id;
      try {
        id = jj_consume_token(ID);
String name = id.image;
                if (!Main.functions.contains(name))
                    {if (true) throw new ParseException("function not exist");}
                jjtn000.value = id.image;
        jj_consume_token(LS);
        if (jj_2_11(2)) {
          arg_stmt();
        } else {
          epsilon();
        }
        jj_consume_token(RS);
        jj_consume_token(END);
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("call_stmt");
    }
}

  static final public void if_stmt() throws ParseException {
    trace_call("if_stmt");
    try {
/*@bgen(jjtree) if_stmt */
  ASTif_stmt jjtn000 = new ASTif_stmt(JJTIF_STMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(IF);
        jj_consume_token(32);
        exp();
        jj_consume_token(LB);
        if (jj_2_12(2)) {
          stmt();
        } else {
          epsilon();
        }
        jj_consume_token(RB);
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("if_stmt");
    }
}

  static final public void ass_stmt() throws ParseException {
    trace_call("ass_stmt");
    try {
/*@bgen(jjtree) ass_stmt */
 ASTass_stmt jjtn000 = new ASTass_stmt(JJTASS_STMT);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);Token id;
      try {
        id = jj_consume_token(ID);
Main.variables.add(id.image);
                      jjtn000.value = id.image;
        jj_consume_token(ASS);
        exp();
        jj_consume_token(END);
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("ass_stmt");
    }
}

  static final public void loop_stmt() throws ParseException {
    trace_call("loop_stmt");
    try {
/*@bgen(jjtree) loop_stmt */
  ASTloop_stmt jjtn000 = new ASTloop_stmt(JJTLOOP_STMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(WHILE);
        jj_consume_token(32);
        exp();
        jj_consume_token(LB);
        if (jj_2_13(2)) {
          stmt();
        } else {
          epsilon();
        }
        jj_consume_token(RB);
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("loop_stmt");
    }
}

  static final public void return_stmt() throws ParseException {
    trace_call("return_stmt");
    try {
/*@bgen(jjtree) return_stmt */
  ASTreturn_stmt jjtn000 = new ASTreturn_stmt(JJTRETURN_STMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(RETURN);
        exp();
        jj_consume_token(END);
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("return_stmt");
    }
}

  static final public void exp() throws ParseException {
    trace_call("exp");
    try {
/*@bgen(jjtree) exp */
  ASTexp jjtn000 = new ASTexp(JJTEXP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        simple_exp();
        if (jj_2_14(2)) {
          jj_consume_token(BL);
          simple_exp();
        } else if (jj_2_15(2)) {
          jj_consume_token(EQ);
          simple_exp();
        } else if (jj_2_16(2)) {
          jj_consume_token(AB);
          simple_exp();
        } else {
          epsilon();
        }
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("exp");
    }
}

  static final public void simple_exp() throws ParseException {
    trace_call("simple_exp");
    try {
/*@bgen(jjtree) simple_exp */
  ASTsimple_exp jjtn000 = new ASTsimple_exp(JJTSIMPLE_EXP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        term();
        simple_exp1();
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("simple_exp");
    }
}

  static final public void simple_exp1() throws ParseException {
    trace_call("simple_exp1");
    try {
/*@bgen(jjtree) simple_exp1 */
  ASTsimple_exp1 jjtn000 = new ASTsimple_exp1(JJTSIMPLE_EXP1);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_17(2)) {
          jj_consume_token(SUB);
          term();
          simple_exp1();
ASTSUB jjtn001 = new ASTSUB(JJTSUB);
                                 boolean jjtc001 = true;
                                 jjtree.openNodeScope(jjtn001);
          try {
jjtree.closeNodeScope(jjtn001,  2);
                                 jjtc001 = false;
jjtn001.value = "-";
          } finally {
if (jjtc001) {
                                   jjtree.closeNodeScope(jjtn001,  2);
                                 }
          }
        } else if (jj_2_18(2)) {
          jj_consume_token(ADD);
          term();
          simple_exp1();
ASTADD jjtn002 = new ASTADD(JJTADD);
                                  boolean jjtc002 = true;
                                  jjtree.openNodeScope(jjtn002);
          try {
jjtree.closeNodeScope(jjtn002,  2);
                                  jjtc002 = false;
jjtn002.value = "+";
          } finally {
if (jjtc002) {
                                    jjtree.closeNodeScope(jjtn002,  2);
                                  }
          }
        } else {
          epsilon();
        }
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("simple_exp1");
    }
}

  static final public void term() throws ParseException {
    trace_call("term");
    try {
/*@bgen(jjtree) term */
  ASTterm jjtn000 = new ASTterm(JJTTERM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        factor();
        term1();
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("term");
    }
}

  static final public void term1() throws ParseException {
    trace_call("term1");
    try {
/*@bgen(jjtree) term1 */
  ASTterm1 jjtn000 = new ASTterm1(JJTTERM1);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_19(2)) {
          jj_consume_token(DIV);
          factor();
          term1();
ASTDIV jjtn001 = new ASTDIV(JJTDIV);
                             boolean jjtc001 = true;
                             jjtree.openNodeScope(jjtn001);
          try {
jjtree.closeNodeScope(jjtn001,  2);
                             jjtc001 = false;
jjtn001.value = "/";
          } finally {
if (jjtc001) {
                               jjtree.closeNodeScope(jjtn001,  2);
                             }
          }
        } else if (jj_2_20(2)) {
          jj_consume_token(MUL);
          factor();
          term1();
ASTMUL jjtn002 = new ASTMUL(JJTMUL);
                              boolean jjtc002 = true;
                              jjtree.openNodeScope(jjtn002);
          try {
jjtree.closeNodeScope(jjtn002,  2);
                              jjtc002 = false;
jjtn002.value = "*";
          } finally {
if (jjtc002) {
                                jjtree.closeNodeScope(jjtn002,  2);
                              }
          }
        } else {
          epsilon();
        }
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("term1");
    }
}

  static final public void factor() throws ParseException {
    trace_call("factor");
    try {
/*@bgen(jjtree) factor */
    ASTfactor jjtn000 = new ASTfactor(JJTFACTOR);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token t;
      try {
        if (jj_2_21(2)) {
          jj_consume_token(LS);
          exp();
          jj_consume_token(RS);
        } else if (jj_2_22(2)) {
          t = jj_consume_token(NUM);
ASTNUM jjtn001 = new ASTNUM(JJTNUM);
                 boolean jjtc001 = true;
                 jjtree.openNodeScope(jjtn001);
          try {
jjtree.closeNodeScope(jjtn001,  0);
                 jjtc001 = false;
Integer i = Integer.parseInt(t.image);
        jjtn001.value = i;
          } finally {
if (jjtc001) {
                   jjtree.closeNodeScope(jjtn001,  0);
                 }
          }
        } else if (jj_2_23(2)) {
          t = jj_consume_token(ID);
jjtree.closeNodeScope(jjtn000, true);
                jjtc000 = false;
if (!Main.variables.contains(t.image)) {
            {if (true) throw new ParseException("variable not exist");}
        }

        jjtn000.value = t.image;
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("factor");
    }
}

  static final public void epsilon() throws ParseException {
    trace_call("epsilon");
    try {
/*@bgen(jjtree) epsilon */
  ASTepsilon jjtn000 = new ASTepsilon(JJTEPSILON);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;

      } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("epsilon");
    }
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_9()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_10()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_11()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_12()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_13()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_14()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_2_15(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_15()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  static private boolean jj_2_16(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_16()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  static private boolean jj_2_17(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_17()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  static private boolean jj_2_18(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_18()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  static private boolean jj_2_19(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_19()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  static private boolean jj_2_20(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_20()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  static private boolean jj_2_21(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_21()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  static private boolean jj_2_22(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_22()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  static private boolean jj_2_23(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_23()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  static private boolean jj_3_14()
 {
    if (jj_scan_token(BL)) return true;
    if (jj_3R_simple_exp_179_5_9()) return true;
    return false;
  }

  static private boolean jj_3_13()
 {
    if (jj_3R_stmt_118_5_3()) return true;
    return false;
  }

  static private boolean jj_3R_stmt_seq_84_5_2()
 {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LS)) return true;
    return false;
  }

  static private boolean jj_3R_simple_exp_179_5_9()
 {
    if (jj_3R_term_194_5_10()) return true;
    return false;
  }

  static private boolean jj_3R_exp_170_5_12()
 {
    if (jj_3R_simple_exp_179_5_9()) return true;
    return false;
  }

  static private boolean jj_3R_return_stmt_164_5_7()
 {
    if (jj_scan_token(RETURN)) return true;
    if (jj_3R_exp_170_5_12()) return true;
    return false;
  }

  static private boolean jj_3_12()
 {
    if (jj_3R_stmt_118_5_3()) return true;
    return false;
  }

  static private boolean jj_3R_loop_stmt_158_5_5()
 {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(32)) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_scan_token(RS)) return true;
    if (jj_scan_token(31)) return true;
    return false;
  }

  static private boolean jj_3R_ass_stmt_148_5_6()
 {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(ASS)) return true;
    return false;
  }

  static private boolean jj_3_11()
 {
    if (jj_3R_arg_stmt_102_5_1()) return true;
    return false;
  }

  static private boolean jj_3R_if_stmt_142_5_4()
 {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(32)) return true;
    return false;
  }

  static private boolean jj_3R_epsilon_225_5_14()
 {
    return false;
  }

  static private boolean jj_3R_call_stmt_130_5_8()
 {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LS)) return true;
    return false;
  }

  static private boolean jj_3R_arg_stmt_102_32_13()
 {
    if (jj_3R_epsilon_225_5_14()) return true;
    return false;
  }

  static private boolean jj_3_10()
 {
    if (jj_3R_call_stmt_130_5_8()) return true;
    return false;
  }

  static private boolean jj_3_9()
 {
    if (jj_3R_return_stmt_164_5_7()) return true;
    return false;
  }

  static private boolean jj_3_8()
 {
    if (jj_3R_ass_stmt_148_5_6()) return true;
    return false;
  }

  static private boolean jj_3_7()
 {
    if (jj_3R_loop_stmt_158_5_5()) return true;
    return false;
  }

  static private boolean jj_3_23()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_3R_if_stmt_142_5_4()) return true;
    return false;
  }

  static private boolean jj_3R_stmt_118_5_3()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3_10()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_22()
 {
    if (jj_scan_token(NUM)) return true;
    return false;
  }

  static private boolean jj_3_21()
 {
    if (jj_scan_token(LS)) return true;
    if (jj_3R_exp_170_5_12()) return true;
    return false;
  }

  static private boolean jj_3R_factor_210_5_11()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_21()) {
    jj_scanpos = xsp;
    if (jj_3_22()) {
    jj_scanpos = xsp;
    if (jj_3_23()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_scan_token(SEM)) return true;
    if (jj_3R_arg_stmt_102_5_1()) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_3R_stmt_118_5_3()) return true;
    return false;
  }

  static private boolean jj_3_20()
 {
    if (jj_scan_token(MUL)) return true;
    if (jj_3R_factor_210_5_11()) return true;
    return false;
  }

  static private boolean jj_3_19()
 {
    if (jj_scan_token(DIV)) return true;
    if (jj_3R_factor_210_5_11()) return true;
    return false;
  }

  static private boolean jj_3R_arg_stmt_102_5_1()
 {
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_arg_stmt_102_32_13()) return true;
    }
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_arg_stmt_102_5_1()) return true;
    if (jj_scan_token(RS)) return true;
    return false;
  }

  static private boolean jj_3R_term_194_5_10()
 {
    if (jj_3R_factor_210_5_11()) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_3R_stmt_seq_84_5_2()) return true;
    return false;
  }

  static private boolean jj_3_18()
 {
    if (jj_scan_token(ADD)) return true;
    if (jj_3R_term_194_5_10()) return true;
    return false;
  }

  static private boolean jj_3_16()
 {
    if (jj_scan_token(AB)) return true;
    if (jj_3R_simple_exp_179_5_9()) return true;
    return false;
  }

  static private boolean jj_3_17()
 {
    if (jj_scan_token(SUB)) return true;
    if (jj_3R_term_194_5_10()) return true;
    return false;
  }

  static private boolean jj_3_15()
 {
    if (jj_scan_token(EQ)) return true;
    if (jj_3R_simple_exp_179_5_9()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public CMM_PARSERTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[23];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  {
      enable_tracing();
  }
  /** Constructor with InputStream. */
  public CMM_PARSER(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public CMM_PARSER(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new CMM_PARSERTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 0; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public CMM_PARSER(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new CMM_PARSERTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new CMM_PARSERTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public CMM_PARSER(CMM_PARSERTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(CMM_PARSERTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   trace_token(token, "");
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	   trace_token(token, " (in getNextToken)");
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[33];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 0; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 33; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  static private int trace_indent = 0;
/** Enable tracing. */
  static final public void enable_tracing() {
	 trace_enabled = true;
  }

/** Disable tracing. */
  static final public void disable_tracing() {
	 trace_enabled = false;
  }

  static protected void trace_call(String s) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Call:	" + s);
	 }
	 trace_indent = trace_indent + 2;
  }

  static protected void trace_return(String s) {
	 trace_indent = trace_indent - 2;
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Return: " + s);
	 }
  }

  static protected void trace_token(Token t, String where) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Consumed token: <" + tokenImage[t.kind]);
	   if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t.image) + "\"");
	   }
	   System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
	 }
  }

  static protected void trace_scan(Token t1, int t2) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Visited token: <" + tokenImage[t1.kind]);
	   if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t1.image) + "\"");
	   }
	   System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
	 }
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 23; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			   case 8: jj_3_9(); break;
			   case 9: jj_3_10(); break;
			   case 10: jj_3_11(); break;
			   case 11: jj_3_12(); break;
			   case 12: jj_3_13(); break;
			   case 13: jj_3_14(); break;
			   case 14: jj_3_15(); break;
			   case 15: jj_3_16(); break;
			   case 16: jj_3_17(); break;
			   case 17: jj_3_18(); break;
			   case 18: jj_3_19(); break;
			   case 19: jj_3_20(); break;
			   case 20: jj_3_21(); break;
			   case 21: jj_3_22(); break;
			   case 22: jj_3_23(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
