/* Generated By:JavaCC: Do not edit this line. CMM_PARSERTreeConstants.java Version 7.0.10 */
package grammar.generator;

public interface CMM_PARSERTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTMT_SEQ = 1;
  public int JJTSTMT_SEQ1 = 2;
  public int JJTARG_STMT = 3;
  public int JJTFUN_STMT = 4;
  public int JJTSTMT = 5;
  public int JJTCALL_STMT = 6;
  public int JJTIF_STMT = 7;
  public int JJTASS_STMT = 8;
  public int JJTLOOP_STMT = 9;
  public int JJTRETURN_STMT = 10;
  public int JJTEXP = 11;
  public int JJTSIMPLE_EXP = 12;
  public int JJTSIMPLE_EXP1 = 13;
  public int JJTTERM = 14;
  public int JJTTERM1 = 15;
  public int JJTFACTOR = 16;
  public int JJTEPSILON = 17;


  public String[] jjtNodeName = {
    "program",
    "stmt_seq",
    "stmt_seq1",
    "arg_stmt",
    "fun_stmt",
    "stmt",
    "call_stmt",
    "if_stmt",
    "ass_stmt",
    "loop_stmt",
    "return_stmt",
    "exp",
    "simple_exp",
    "simple_exp1",
    "term",
    "term1",
    "factor",
    "epsilon",
  };
}
/* JavaCC - OriginalChecksum=7ecff55798d973a9c7309ce9c72b8925 (do not edit this line) */
